

/*Print all subsequences of a string

    Difficulty Level : Medium
    Last Updated : 05 Feb, 2021

Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
Examples: 

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa
*/

#include<bits/stdc++.h>
using namespace std;

unordered_set<string>st;

void subsequence(string str)
{
	for(int i=0;i<str.length();i++)
	{
		for(int j=str.length();j>i;j--)
		{
			string sub_str=str.substr(i,j);
			st.insert(sub_str);



			for(int k=1;k<sub_str.length()-1;k++)
			{
				string sb=sub_str;
				sb.erase(sb.begin()+k);
				subsequence(sb);
			}
		}
	}
}








int main()
{
	
	string s = "aabc";
    subsequence(s);
    for (auto i : st)
        cout << i << " ";
    cout << endl;
	return 0;
}