/*Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.

A string is called palindrome if is one that reads the same backward as well as forward.

 

Example 1:

Input: s = "ababa"
Output: 1
Explanation: String is already palindrome

Example 2:

Input: s = "abb"
Output: 2
Explanation: "abb" -> "bb" -> "". 
Remove palindromic subsequence "a" then "bb".

*/

class Solution {
public:
    int removePalindromeSub(string s) {
        int n=s.length();
        string rev=s;
        reverse(s.begin(),s.end());
        if(n==0)
        {
            return 0;
        }
        else if(s==rev)
        {
            return 1;
        }
        return 2;
        
    }
};